name: Rodar testes automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.1

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results 
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3  
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/results/mochawesome-report
